// src/components/ds/icon.ts — iconFor(kebab-case) → lucide-vue-next component.
// Shared by IconRail / SidebarPanel / TabStrip / Toolbar / CommandPalette.
import {
  Database, BookMarked, PieChart, Command, LayoutDashboard,
  Building2, Users, FileText, BookOpen, Receipt, Landmark,
  Sun, Car, Bike, Coins, Zap, Wallet, Plug, Upload,
  TrendingUp, TrendingDown, Scale, Table2, Home, Droplets, Wrench, Banknote,
  GitCompare, Gauge, Activity, BarChart3, Siren, CalendarClock,
  Scale3d, Layers, BellRing, PanelLeft, Star, History, Bell,
  Search, ChevronDown, X, Clock, Calendar, Plus, Filter,
  Check, ArrowLeft, Pencil,
  BedDouble, DoorOpen, Ruler, LayoutGrid, StickyNote,
  Building, User, Phone, Briefcase, MapPin,
  FileCheck2, FilePen, GitCommitHorizontal, Archive, RotateCcw, XCircle, List,
  Repeat, CalendarCheck, CornerDownRight, Download, Copy, Info, ArrowRight, ChevronLeft, ChevronRight,
  Trash2, Lock, FilePlus,
  Minus, CheckCircle2, Circle,
  ClipboardCheck, ListTodo, Files,
  FileSpreadsheet, ClipboardPaste, UploadCloud, AlertTriangle, Wand2,
  ArrowUpRight, CircleDashed, Printer,
  ArrowDownRight, ShieldCheck, AlertOctagon, FlaskConical, SlidersHorizontal, // P3 分析层
  Target, // P3-P1 预算对比
  Share2, PenLine, Play, RefreshCw, // P-B 公摊分摊
  Tags, // 价目管理
  Settings, // 系统管理层
  HelpCircle, // fallback
} from 'lucide-vue-next'
import type { Component } from 'vue'

const MAP: Record<string, Component> = {
  'database': Database,
  'book-marked': BookMarked,
  'pie-chart': PieChart,
  'command': Command,
  'layout-dashboard': LayoutDashboard,
  'building-2': Building2,
  'users': Users,
  'file-text': FileText,
  'book-open': BookOpen,
  'receipt': Receipt,
  'landmark': Landmark,
  'sun': Sun,
  'car': Car,
  'bike': Bike,
  'coins': Coins,
  'zap': Zap,
  'wallet': Wallet,
  'plug': Plug,
  'upload': Upload,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'scale': Scale,
  'table-2': Table2,
  'home': Home,
  'droplets': Droplets,
  'wrench': Wrench,
  'banknote': Banknote,
  'git-compare': GitCompare,
  'gauge': Gauge,
  'activity': Activity,
  'bar-chart-3': BarChart3,
  'siren': Siren,
  'calendar-clock': CalendarClock,
  'scale-3d': Scale3d,
  'layers': Layers,
  'bell-ring': BellRing,
  'panel-left': PanelLeft,
  'star': Star,
  'history': History,
  'bell': Bell,
  'search': Search,
  'chevron-down': ChevronDown,
  'x': X,
  'clock': Clock,
  'calendar': Calendar,
  'plus': Plus,
  'filter': Filter,
  'check': Check,
  'arrow-left': ArrowLeft,
  'pencil': Pencil,
  'bed-double': BedDouble,
  'door-open': DoorOpen,
  'ruler': Ruler,
  'layout-grid': LayoutGrid,
  'sticky-note': StickyNote,
  'building': Building,
  'user': User,
  'phone': Phone,
  'briefcase': Briefcase,
  'map-pin': MapPin,
  'file-check-2': FileCheck2,
  'file-pen': FilePen,
  'git-commit-horizontal': GitCommitHorizontal,
  'archive': Archive,
  'rotate-ccw': RotateCcw,
  'x-circle': XCircle,
  'list': List,
  'repeat': Repeat,
  'calendar-check': CalendarCheck,
  'corner-down-right': CornerDownRight,
  'download': Download,
  'copy': Copy,
  'info': Info,
  'arrow-right': ArrowRight,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'trash-2': Trash2,
  'lock': Lock,
  'file-plus': FilePlus,
  'minus': Minus,
  'check-circle-2': CheckCircle2,
  'circle': Circle,
  'clipboard-check': ClipboardCheck,
  'list-todo': ListTodo,
  'files': Files,
  'file-spreadsheet': FileSpreadsheet,
  'clipboard-paste': ClipboardPaste,
  'upload-cloud': UploadCloud,
  'alert-triangle': AlertTriangle,
  'wand-2': Wand2,
  'arrow-up-right': ArrowUpRight,
  'circle-dashed': CircleDashed,
  'printer': Printer,
  'arrow-down-right': ArrowDownRight,
  'shield-check': ShieldCheck,
  'alert-octagon': AlertOctagon,
  'flask-conical': FlaskConical,
  'sliders-horizontal': SlidersHorizontal,
  'target': Target,
  'share-2': Share2,
  'pen-line': PenLine,
  'play': Play,
  'refresh-cw': RefreshCw,
  'tags': Tags,
  'settings': Settings,
}

export function iconFor(name: string): Component {
  const icon = MAP[name]
  if (!icon) {
    console.warn(`[iconFor] unknown icon name: "${name}" — using HelpCircle fallback`)
    return HelpCircle
  }
  return icon
}
